---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - myapp.hzy.com
  resources:
  - mystates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - myapp.hzy.com
  resources:
  - mystates/finalizers
  verbs:
  - update
- apiGroups:
  - myapp.hzy.com
  resources:
  - mystates/status
  verbs:
  - get
  - patch
  - update
